name: Build docker images using cache
description: Use registry to pull/push cache for an image (stages included)
author: whoan

inputs:

  image_name:
    description: Name of the image to build
    required: true
  username:
    description: (Optional) Docker's registry user (needed to push image to repository, or to pull from private repository)
    required: false
  password:
    description: (Optional) Docker's registry password (needed to push image to repository, or to pull from private repository)
    required: false
  registry:
    description: "(Optional) Docker registry (default: us.gcr.io)"
    required: false
    default: us.gcr.io
  image_tag:
    description: "(Optional) Tag/s of the image to build (default: latest)"
    required: false
    default: latest
  context:
    description: "(Optional) Docker context (default: ./)"
    required: false
    default: .
  dockerfile:
    description: "(Optional) Name of the Dockerfile (default: Dockerfile)"
    required: false
    default: Dockerfile
  push_image_and_stages:
    description: "(Optional) Set to false to avoid pushing to registry (default: true)"
    required: false
    default: true
  push_git_tag:
    description: "(Optional) In addition to `image_tag` value, you can also push current git tag (default: false)"
    required: false
    default: true
  pull_image_and_stages:
    description: "(Optional) Set to false to avoid pulling from registry (default: true)"
    required: false
    default: true
  build_extra_args:
    description: "(Optional) Extra arguments to pass to docker build"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'anchor'
  color: 'blue'
