name: Build docker images using cache
description: Use registry to pull/push cache for an image (stages included)
author: whoan

inputs:

  image_name:
    description: Name of the image to build
    required: true
  username:
    description: (Optional) Docker's registry user (needed to push image to repository, or to pull from private repository)
    required: false
  password:
    description: (Optional) Docker's registry password (needed to push image to repository, or to pull from private repository)
    required: false
  registry:
    description: "(Optional) Docker registry (default: us.gcr.io)"
    required: false
    default: us.gcr.io
  image_tags:
    description: "(Optional) Tag/s of the image to build (default: latest)"
    required: false
    default: latest
  context:
    description: "(Optional) Docker context (default: ./)"
    required: false
    default: .
  dockerfile:
    description: "(Optional) Name of the Dockerfile (default: Dockerfile)"
    required: false
    default: Dockerfile
  push_image_and_stages:
    description: "(Optional) Set to false to avoid pushing to registry (default: true)"
    required: false
    default: true
  push_git_tag:
    description: "(Optional) In addition to `image_tag` value, you can also push current git tag (default: false)"
    required: false
    default: false
  pull_image_and_stages:
    description: "(Optional) Set to false to avoid pulling from registry (default: true)"
    required: false
    default: true
  build_extra_args:
    description: "(Optional) Extra arguments to pass to docker build"
    required: false
  git_sha:
    description: "(Optional) Set to 'false' if you do not want a commit hash tag and env variable"
    required: false
    default: ${{ github.sha }}
  version_update_type:
    description: "(Optional) Whether it is a major version update, minor, or bug fix. Can be 'major', 'minor', or 'bug'"
    required: false
#===========================================================================================================================
  gcr_service_account:
    description: 'DEPRECATED Service account secret for the GCR service user (use "password" with "username: _json_key" instead)'
    required: false
    default: ''
  gcr_host:
    description: 'DEPRECATED GCR Host to be used to store the image (use "registry: us.gcr.io" instead)'
    required: false
    default: 'us.gcr.io'
  gcr_project:
    description: 'DEPRECATED Project which contains the desired repository (include in "image_name" instead)'
    required: false
    default: ''
  gcr_repo:
    description: 'DEPRECATED Additional repository path to be used (ending in /) (include in "image_name" instead)'
    required: false
    default: ''
  gcr_image_name:
    description: 'DEPRECATED Name for the image in GCR (use "image_name" instead)'
    required: false
    default: ''
  dockerfile_path:
    description: 'DEPRECATED Path to the directory which contains the dockerfile to be built (use "context" instead)'
    required: false
    default: ''
  image_tag:
    description: 'DEPRECATED Tag to be put on the image (use "image_tags" instead)'
    required: false
    default: ${{ github.sha }}
runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'anchor'
  color: 'blue'
